Chooser/Chooser/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

Chooser/debate/urls.py
# from django.contrib import admin
from django.urls import path
from .views import debate_index, debate_create, debate_detail, debate_create_comment, debate_delete_comment, debate_vote_1, debate_vote_2


urlpatterns = [
    path('index/', debate_index, name="debate_index"),
    path('create/', debate_create, name="debate_create"),
    path('detail/<int:debate_id>', debate_detail, name="debate_detail"),


    #댓글 기능
    path('create_comment/<int:debate_id>/', debate_create_comment, name="debate_create_comment"),
    path('delete_comment/<int:debate_id>/<int:com_pre_id>', debate_delete_comment, name="debate_delete_comment"),

    #좋아요 기능
    path('debate_vote_1/<int:debate_id>', debate_vote_1, name="debate_vote_1"),
    path('debate_vote_2/<int:debate_id>', debate_vote_2, name="debate_vote_2"),

] 

Chooser/main/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.home , name = 'home'),
    path('mypage/', views.mypage, name = 'mypage'), 
]

Chooser/main/models.py
from django.db import models 
from django.contrib.auth.models import User
# 페이지네이션
from django.core.paginator import Paginator
# 회원

# 회원
# User 모델 사용
# ㅇㅇ
# 취향 페이지
class Topic(models.Model):
    topic_id = models.AutoField(primary_key=True)# PK
    topic_content = models.TextField()
    topic_start_date = models.DateTimeField(auto_now_add=True)
    topic_end_date = models.DateTimeField()

class Prefer(models.Model):
    prefer_id = models.AutoField(primary_key=True) # PK
    # prefer_topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    prefer_member_id = models.ForeignKey(User, on_delete=models.CASCADE)
    prefer_title = models.CharField(max_length=50)
    prefer_date = models.DateTimeField(auto_now_add=True) # 수정해도 날짜가 안바뀜
    prefer_content = models.TextField()
    prefer_file =  models.ImageField(blank=True, upload_to='Img/')
    # like 기능
    # prefer_like_user
    # https://tothefullest08.github.io/django/2019/06/11/Django21_relations3_many_to_many/
    

class Comment_prefer(models.Model):
    com_pre_id = models.AutoField(primary_key=True) # PK
    com_pre_member_id = models.ForeignKey(User, on_delete=models.CASCADE) # FK(member_id)
    com_pre_prefer_id = models.ForeignKey(Prefer, on_delete=models.CASCADE) # FK(prefer_id)
    com_pre_content = models.TextField()


# 토론 페이지
class Debate(models.Model):
    debate_id = models.AutoField(primary_key=True) # PK
    debate_pre_date = models.DateTimeField(auto_now_add=True) # 수정해도 날짜가 안바뀜
    debate_img1 = models.ImageField(blank=True, upload_to='Img/')
    debate_img2 = models.ImageField(blank=True, upload_to='Img/')
    debate_img1_name1 = models.CharField(max_length=20)
    debate_img2_name2 = models.CharField(max_length=20)

class Comment_debate(models.Model):
    com_deb_id = models.AutoField(primary_key=True) # PK
    com_deb_member_id = models.ForeignKey(User, on_delete=models.CASCADE) # FK(member_id)
    com_deb_debate_id = models.ForeignKey(Debate, on_delete=models.CASCADE) # FK(debate_id)
    com_deb_result = models.CharField(max_length = 1)
    com_deb_content = models.TextField()
    con_deb_date = models.DateTimeField(auto_now_add=True) # 수정해도 날짜가 안바뀜

class Vote(models.Model):
    vote_id = models.AutoField(primary_key=True) # PK
    vote_member_id = models.ForeignKey(User, on_delete=models.CASCADE)# FK(member_id)
    vote_debate_id = models.ForeignKey(Debate, on_delete=models.CASCADE)# FK(debate_id)
    vote_result_1 = models.IntegerField(default=0)# BooleanField(참거짓)으로 구분할 수 있을까? 언제든지 취소 수정 가능?
    vote_result_2 = models.IntegerField(default=0)# BooleanField는 Ture, False로 구분 되며 변경 가능합니다.


class Mood(models.Model):
    mood_id = models.AutoField(primary_key=True) # PK
    mood_val = models.CharField(max_length=10) # 기분수치
    mood_state = models.CharField(max_length=50) # 기분 이름
    mood_content = models.TextField() # 기분 내용
    mood_date = models.DateTimeField(auto_now=True) # 기분 시간
    mood_member_id=models.ForeignKey(User, on_delete=models.CASCADE) # FK(member_id)


# author = models.ForeignKey(User, on_delete=models.CASCADE)

# 날짜 모델 변경
# 투표 결과 정수형으로 한 거 모델 한글에 써놓기
# 모델에 있는 주석들 다 보기

Chooser/debate/forms.py
from django import forms
from main.models import Debate, Comment_debate

class DebateForm(forms.ModelForm):
    class Meta:
        model = Debate
        fields = ('debate_img1', 'debate_img2', 'debate_img1_name1', 'debate_img2_name2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['debate_img1'].label = "사진1"
        self.fields['debate_img2'].label = "사진2"
        self.fields['debate_img1_name1'].label = "사진이름1"
        self.fields['debate_img2_name2'].label = "사진이름2"
# ㅜㅜHelp Me Thank ypu ,,,, ^___^

# 댓글 기능
class DebateCommentForm(forms.ModelForm):

    class Meta:
        model = Comment_debate
        fields = ('com_deb_content', )

Chooser/debate/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.core.paginator import Paginator
from .forms import DebateForm, DebateCommentForm
from main.models import User, Debate, Comment_debate, Vote
# Create your views here.


def debate_index(request):
    all_debate = Debate.objects.all()
    debates = Debate.objects
    debate_list = Debate.objects.all()
    paginator = Paginator(debate_list, 6)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    return render(request, 'debate_index.html', {'all_debate':all_debate, 'debates':debates, 'posts':posts})

def my_debate_index(request):
    my_debate = Debate.objects.filter(debate_member_id=request.user)
    return render(request, 'debate_index.html', {'my_debate':my_debate})

@login_required(login_url='/login')
def debate_create(request):
    if request.method == "POST":
        filled_form = DebateForm(request.POST, request.FILES)
        if filled_form.is_valid():
            temp_form = filled_form.save(commit=False)
            temp_form.debate_member_id = request.user
            temp_form.save()
            return redirect('debate_index')
    debate_form = DebateForm()
    return render(request, 'debate_create.html', {'debate_form':debate_form})

def debate_detail(request, debate_id):
    debate = get_object_or_404(Debate, pk=debate_id)
    return render(request, 'debate_detail.html',{'debate':debate, 'debate_img1_name1':debate.debate_img1_name1, 'debate_img2_name2':debate.debate_img2_name2})

def debate_create_comment(request, debate_id):
    debate_comment_form = CommentForm(request.POST)
    if debate_comment_form.is_valid():
        temp_form = debate_comment_form.save(commit=False)
        temp_form.com_deb_member_id = request.user
        temp_form.com_deb_debate_id = debate.objects.get(pk=debate_id)
        temp_form.debate = Debate.objects.get(pk=debate_id)
        temp_form.save()
        return redirect('debate_detail', debate_id)
    else: 
        return redirect('debate_detail', debate_id)

def debate_delete_comment(request, debate_id, com_deb_id):
    debate_my_comment = Comment_debate.objects.get(pk=com_deb_id)
    if request.user == debate_my_comment.com_deb_member_id:
        debate_my_comment.delete()
        return redirect('debate_detail', debate_id)

    else:
        raise PermissionDenied




@login_required(login_url='/login')
def debate_vote_1(request, vote_id):
    temp_vote_1 = get_object_or_404(Post, id=vote_id)
    temp_vote_2 = get_object_or_404(Post, id=vote_id)
    temp_debate_user_1 = request.user
    temp_debate_id_1 = Debate.objects.get(pk=debate_id)

    

    if temp_vote.vote_result_1 == 0:
        temp_vote_1.vote_result_1 -= 1
        temp_vote_1.save()
    else:
        check_vote_1.add(post)
        temp_vote_1.vote_result_1 += 1
        temp_vote_1.save()

    return redirect('debate_detail', debate_id)


@login_required(login_url='/login')
def debate_vote_2(request, vote_id):
    temp_vote_2 = get_object_or_404(Post, id=vote_id)
    temp_debate_user_2 = request.user
    temp_debate_id_2 = Debate.objects.get(pk=debate_id)



    if temp_vote.vote_result_2 == 0:
        temp_vote.vote_result_2 -= 1
        temp_vote_2.save()
    else:
        temp_vote_2.vote_result_2 += 1
        temp_vote_2.save()

    return redirect('debate_detail', debate_id)

Chooser/debate/templates/debate_create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'css/debate_create.css'%}">
    <title>Chooser - 토론 글쓰기</title>
</head>
<body>
     <!-- 제목&내용&버튼 -->
     <form method="POST" action="">
        {% csrf_token %}
        {{debate_form.as_p}}
        <input type="submit" value="확인">
    </form>   


</body>
</html>

Chooser/debate/templates/debate_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel= "stylesheet" href="{% static 'css/debate_detail.css' %}">
    
    <title>Chooser - 토론</title>
</head>
<body>
<div class="all_deb_detail">
    <!-- 상단(로고, 주제) -->
    <a href="{% url 'to_main' %}" class="main_logo_warper">
        <img src="{% static 'Img/logo.png' %}" class="main_logo">
    </a> 
    <h1>이것! 저것! 둘 중 하나!</h1>

    <!-- 글 내용 -->
    <div class = "big_debate_img">
        <img id="left_img" class="left_img" src="{{ debate.debate_img1.url }}">
        <img id="right_img" class="right_img" src="{{ debate.debate_img2.url }}">
    </div>
        <p class="debate_title">{{debate.debate_img1_name1}}   vs   {{debate.debate_img2_name2}}</p>
    <div id="result">
         0% : 0% 
    </div>
    <div class="chart">
        <canvas id="canvas" width="500px" height="30px"></canvas>
    </div>

    <a href="{% url 'debate_index' %}">
        <div class="button">
            <button>글 목록</button>
        </div>
    </a>
     <!-- 댓글기능 -->
    <br>
    <!-- create_comment url 문제 -->
    {% comment %}
    {% if user.is_authenticated %}
        <form method="POST" action="{% url 'debate_create_comment' my_debate.debate_id %}">
        {% csrf_token %}
        {{debate_comment_form}}
        <input type="submit" value="댓글달기!">
        </form>
    {% endif %}
    {% endcomment %}

<!-- 댓글 수정&삭제 -->
{% for comment_debate in my_debate.comment_debate_set.all %}

<p>
    {{comment_debate.com_deb_member_id}} 🤦‍♂️ {{comment_debate.com_deb_content}}
    {% if user == comment_debate.com_deb_member_id %}
    {% comment %} <a href="{% url 'debate_update_comment' my_debate.debate_id comment_debate.com_deb_id %}"> 
       
        <button>수정</button>
    </a> {% endcomment %}
    <a href="{% url 'debate_delete_comment' my_debate.debate_id comment_debate.com_deb_id %}">    
        <button>삭제</button>
    </a>
    {% endif %}
</p>

{% endfor %}
</div>
</body>

{% comment %} <script src="http://code.jquery.com/jquery-3.5.1.min.js"></script> {% endcomment %}
<script type="text/javascript">
    const img_name1 = "{{ debate.debate_img1_name1 }}";
    const img_name2 = "{{ debate.debate_img2_name2 }}";
</script>
<script type="text/javascript" src="{% static 'js/graph_ok.js' %}"></script>

</html>

Chooser/debate/templates/debate_index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/debate_index.css' %}">
    <title>Chooser - 토론 목록</title>

    <!-- <div class="make_debate">
        <a href="{% url 'debate_create' %}">
        <div class="plus_btn">
            <button>글쓰기</button>
        </div>
        </a>
    </div> -->


    {% comment %} bootstrap {% endcomment %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</head>
<body>
<div class="all_deb_index">
    <!-- 상단(로고, 주제) -->
    <a href="{% url 'to_main' %}" class="main_logo_warper">
        <img src="{% static 'Img/logo.png' %}" class="main_logo">
    </a> 
    <h1>이것! 저것! 둘 중 하나!</h1>

    <!-- 정렬 -->
    <!-- <select>
        <option>랜덤 순</option>
        <option>조회 높은 순</option>
        <option>참여 높은 순</option>
        <option>최신 순</option>
        <option>오래된 순</option>
    </select> -->
    
    <!-- 목록 -->
    <h3>골라골라!!</h3>

    {% for debate in posts %}
    <a href="{% url 'debate_detail' debate.debate_id %}">
        <div class="big_box">
            <div class="small_box">
                <div class="preview_all">
                    <div class="big_preview">
                    <img class="preview" src="{{ debate.debate_img1.url }}">
                    </div>
                    <div class="big_preview">
                    <img class="preview" src="{{ debate.debate_img2.url }}">
                    </div>
                </div>
                <div class="big_title">
                    <p class="title">{{debate.debate_img1_name1}} vs {{debate.debate_img2_name2}}</p>
                </div>
            </div>
        </div>
    </a>
    {% endfor %}

    {% comment %} 버튼 {% endcomment %}
    
    <!-- 페이지네이션 -->
    <div class="debate_pagination">
        <!-- 이전 페이지(True일 시) 불러오기 -->
        {% if posts.has_previous %}
        <a href="?page=1">맨 앞으로</a>
        <a href="?page={{posts.previous_page_number}}">이전으로</a>
        {% endif %}
  
        <!-- 현재&총 페이지 넘버 불러오기 -->
        <span>{{posts.number}}</span>
        <span>/</span>
        <span>{{posts.paginator.num_pages}}</span>
  
        <!-- 다음 페이지(True일 시) 불러오기-->
        {% if posts.has_next %}
        <a href="?page={{posts.next_page_number}}">다음으로</a>
        <a href="?page={{posts.paginator.num_pages}}">맨 뒤로</a>
        {% endif %}
    </div>
</div>
</body>
</html>