Chooser/Chooser/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

Chooser/main/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.home , name = 'home'),
    path('mypage/', views.mypage, name = 'mypage'), 
]

Chooser/prefer/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import prefer_index, prefer_create, prefer_detail, prefer_delete, prefer_update, prefer_create_comment, prefer_delete_comment


urlpatterns = [
    path('index/', prefer_index, name="prefer_index"),
    path('create/', prefer_create, name="prefer_create"),
    path('detail/<int:prefer_id>', prefer_detail, name="prefer_detail"),
    path('delete/<int:prefer_id>', prefer_delete, name="prefer_delete"),
    path('update/<int:prefer_id>', prefer_update, name="prefer_update"),

    #댓글 기능
    path('create_comment/<int:prefer_id>/', prefer_create_comment, name="prefer_create_comment"),
    # path('update_comment/<int:prefer_id>/<int:com_pre_id>', prefer_update_comment, name="prefer_update_comment"),
    path('delete_comment/<int:prefer_id>/<int:com_pre_id>', prefer_delete_comment, name="prefer_delete_comment"),
]

Chooser/main/models.py
from django.db import models 
from django.contrib.auth.models import User
# 페이지네이션
from django.core.paginator import Paginator
# 회원

# 회원
# User 모델 사용
# ㅇㅇ
# 취향 페이지
class Topic(models.Model):
    topic_id = models.AutoField(primary_key=True)# PK
    topic_content = models.TextField()
    topic_start_date = models.DateTimeField(auto_now_add=True)
    topic_end_date = models.DateTimeField()

class Prefer(models.Model):
    prefer_id = models.AutoField(primary_key=True) # PK
    # prefer_topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    prefer_member_id = models.ForeignKey(User, on_delete=models.CASCADE)
    prefer_title = models.CharField(max_length=50)
    prefer_date = models.DateTimeField(auto_now_add=True) # 수정해도 날짜가 안바뀜
    prefer_content = models.TextField()
    prefer_file =  models.ImageField(blank=True, upload_to='Img/')
    # like 기능
    # prefer_like_user
    # https://tothefullest08.github.io/django/2019/06/11/Django21_relations3_many_to_many/
    

class Comment_prefer(models.Model):
    com_pre_id = models.AutoField(primary_key=True) # PK
    com_pre_member_id = models.ForeignKey(User, on_delete=models.CASCADE) # FK(member_id)
    com_pre_prefer_id = models.ForeignKey(Prefer, on_delete=models.CASCADE) # FK(prefer_id)
    com_pre_content = models.TextField()


# 토론 페이지
class Debate(models.Model):
    debate_id = models.AutoField(primary_key=True) # PK
    debate_pre_date = models.DateTimeField(auto_now_add=True) # 수정해도 날짜가 안바뀜
    debate_img1 = models.ImageField(blank=True, upload_to='Img/')
    debate_img2 = models.ImageField(blank=True, upload_to='Img/')
    debate_img1_name1 = models.CharField(max_length=20)
    debate_img2_name2 = models.CharField(max_length=20)

class Comment_debate(models.Model):
    com_deb_id = models.AutoField(primary_key=True) # PK
    com_deb_member_id = models.ForeignKey(User, on_delete=models.CASCADE) # FK(member_id)
    com_deb_debate_id = models.ForeignKey(Debate, on_delete=models.CASCADE) # FK(debate_id)
    com_deb_result = models.CharField(max_length = 1)
    com_deb_content = models.TextField()
    con_deb_date = models.DateTimeField(auto_now_add=True) # 수정해도 날짜가 안바뀜

class Vote(models.Model):
    vote_id = models.AutoField(primary_key=True) # PK
    vote_member_id = models.ForeignKey(User, on_delete=models.CASCADE)# FK(member_id)
    vote_debate_id = models.ForeignKey(Debate, on_delete=models.CASCADE)# FK(debate_id)
    vote_result_1 = models.IntegerField(default=0)# BooleanField(참거짓)으로 구분할 수 있을까? 언제든지 취소 수정 가능?
    vote_result_2 = models.IntegerField(default=0)# BooleanField는 Ture, False로 구분 되며 변경 가능합니다.


class Mood(models.Model):
    mood_id = models.AutoField(primary_key=True) # PK
    mood_val = models.CharField(max_length=10) # 기분수치
    mood_state = models.CharField(max_length=50) # 기분 이름
    mood_content = models.TextField() # 기분 내용
    mood_date = models.DateTimeField(auto_now=True) # 기분 시간
    mood_member_id=models.ForeignKey(User, on_delete=models.CASCADE) # FK(member_id)


# author = models.ForeignKey(User, on_delete=models.CASCADE)

# 날짜 모델 변경
# 투표 결과 정수형으로 한 거 모델 한글에 써놓기
# 모델에 있는 주석들 다 보기

Chooser/prefer/forms.py
from django import forms
from main.models import Prefer, Comment_prefer

class PreferForm(forms.ModelForm):
    class Meta:
        model = Prefer
        fields = ('prefer_title', 'prefer_content', 'prefer_file',)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['prefer_title'].label = "주제"
        self.fields['prefer_content'].label = "내용"
        self.fields['prefer_file'].label = "이미지"
        self.fields['prefer_title'].widget.attrs.update({
            'class': 'prefer_title',
            'placeholder': '마음껏 소개해바...ㅡㅡ^^',
        })
        self.fields['prefer_content'].widget.attrs.update({
            'class': 'prefer_content',
            'placeholder': '너의 취향,,, @>-->----,,,,',
        })
        self.fields['prefer_file'].widget.attrs.update({
            'class': 'prefer_file',
        })

# 댓글 기능
class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment_prefer
        fields = ('com_pre_content', )
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['com_pre_content'].label = "댓글"
        self.fields['com_pre_content'].widget.attrs.update({
            'class': 'com_pre_content',
            'placeholder': '댓글을 달아주세용~!',
        })

Chooser/prefer/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.core.paginator import Paginator
from .forms import PreferForm, CommentForm
from main.models import User, Topic, Prefer, Comment_prefer
# Cremainate yosur views herer
# Create your views here

def prefer_index(request):
    all_prefer = Prefer.objects.all()
    # https://egg-money.tistory.com/111?category=811218 참조
    # 페이지네이션
    prefers = Prefer.objects
    prefer_list = Prefer.objects.all()
    paginator = Paginator(prefer_list, 3)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    return render(request, 'prefer_index.html', {'all_prefer':all_prefer, 'prefers':prefers, 'posts':posts})

def my_prefer_index(request):
    my_prefer = Prefer.objects.filter(prefer_member_id=request.user)
    return render(request, 'prefer_index.html', {'my_prefer':my_prefer})


@login_required(login_url='/login')
def prefer_create(request):
    if request.method == "POST":
        filled_form = PreferForm(request.POST, request.FILES) # request.FILES 없을 때는 이미지가 따로 들어가지 않아요
        if filled_form.is_valid():
            temp_form = filled_form.save(commit=False)
            temp_form.prefer_member_id = request.user
            temp_form.save()
            return redirect('prefer_index')
    prefer_form = PreferForm()
    return render(request, 'prefer_create.html', {'prefer_form':prefer_form})

@login_required(login_url='/login')
def prefer_detail(request, prefer_id):
    my_prefer = get_object_or_404(Prefer, pk=prefer_id)
    prefer_comment_form = CommentForm()
    return render(request, 'prefer_detail.html', {'my_prefer':my_prefer, 'prefer_comment_form':prefer_comment_form})
    # 왼쪽이 '내가 정해준 저장공간 이름', 오른쪽이 저장할 것의(객체) 이름

def prefer_delete(request, prefer_id):
    my_prefer = Prefer.objects.get(pk=prefer_id)
    if request.user == my_prefer.prefer_member_id:
        my_prefer.delete()
        return redirect('prefer_index')

    raise PermissionDenied

def prefer_update(request, prefer_id):
    my_prefer = Prefer.objects.get(pk=prefer_id)
    prefer_form = PreferForm(instance=my_prefer)
    if request.method == "POST":
        updated_form = PreferForm(request.POST, instance=my_prefer)
        if updated_form.is_valid():
            updated_form.save()
            return redirect('prefer_detail', prefer_id)
    return render(request, 'prefer_create.html', {'prefer_form':prefer_form})


def prefer_create_comment(request, prefer_id):
    prefer_comment_form = CommentForm(request.POST)
    if prefer_comment_form.is_valid():
        temp_form = prefer_comment_form.save(commit=False)
        temp_form.com_pre_member_id = request.user
        temp_form.com_pre_prefer_id = Prefer.objects.get(pk=prefer_id)
        temp_form.prefer = Prefer.objects.get(pk=prefer_id)
        temp_form.save()
        return redirect('prefer_detail', prefer_id)
    else: 
        return redirect('prefer_detail', prefer_id)

def prefer_delete_comment(request, prefer_id, com_pre_id):
    prefer_my_comment = Comment_prefer.objects.get(pk=com_pre_id)
    if request.user == prefer_my_comment.com_pre_member_id:
        prefer_my_comment.delete()
        return redirect('prefer_detail', prefer_id)

    else:
        raise PermissionDenied

# 수정버튼
# def prefer_update_comment(request, prefer_id, com_pre_id):
#     prefer_my_comment = Comment_prefer.objects.get(pk=com_pre_id)
#     prefer_my_comment_form = CommentForm(instance=prefer_my_comment)
#     if request.method == "POST":
#         comment_updated_form = CommentForm(request.POST, instance=prefer_my_comment)
#         if comment_updated_form.is_valid():
#             comment_updated_form.request.user
#             comment_updated_form.save()
#             return redirect('prefer_detail', prefer_id)
#         return render(request, 'prefer_detail.html', {'prefer_my_comment_form':prefer_my_comment_form})

#     else:
#         raise PermissionDenied

# 수정버튼
# def prefer_update_comment(request, prefer_id, com_pre_id):
#     prefer_my_comment = Comment_prefer.objects.get(pk=com_pre_id)
#     prefer_my_comment_form = CommentForm(instance=prefer_my_comment)
#     if request.method == "POST":
#         comment_updated_form = CommentForm(request.POST, instance=prefer_my_comment)
#         if comment_updated_form.is_valid():
#             comment_updated_form.request.user
#             comment_updated_form.save()
#             return redirect('prefer_detail', prefer_id)
#         return render(request, 'prefer_detail.html', {'prefer_my_comment_form':prefer_my_comment_form})

#     else:
#         raise PermissionDenied

# 수정버튼
# def prefer_update_comment(request, prefer_id, com_pre_id):
#     prefer_my_comment = Comment_prefer.objects.get(pk=com_pre_id)
#     prefer_my_comment_form = CommentForm(instance=prefer_my_comment)
#     if request.method == "POST":
#         comment_updated_form = CommentForm(request.POST, instance=prefer_my_comment)
#         if comment_updated_form.is_valid():
#             comment_updated_form.request.user
#             comment_updated_form.save()
#             return redirect('prefer_detail', prefer_id)
#         return render(request, 'prefer_detail.html', {'prefer_my_comment_form':prefer_my_comment_form})

#     else:
#         raise PermissionDenied

# 수정버튼
# def prefer_update_comment(request, prefer_id, com_pre_id):
#     prefer_my_comment = Comment_prefer.objects.get(pk=com_pre_id)
#     prefer_my_comment_form = CommentForm(instance=prefer_my_comment)
#     if request.method == "POST":
#         comment_updated_form = CommentForm(request.POST, instance=prefer_my_comment)
#         if comment_updated_form.is_valid():
#             comment_updated_form.request.user
#             comment_updated_form.save()
#             return redirect('prefer_detail', prefer_id)
#         return render(request, 'prefer_detail.html', {'prefer_my_comment_form':prefer_my_comment_form})

#     else:
#         raise PermissionDenied

# 수정버튼
# def prefer_update_comment(request, prefer_id, com_pre_id):
#     prefer_my_comment = Comment_prefer.objects.get(pk=com_pre_id)
#     prefer_my_comment_form = CommentForm(instance=prefer_my_comment)
#     if request.method == "POST":
#         comment_updated_form = CommentForm(request.POST, instance=prefer_my_comment)
#         if comment_updated_form.is_valid():
#             comment_updated_form.request.user
#             comment_updated_form.save()
#             return redirect('prefer_detail', prefer_id)
#         return render(request, 'prefer_detail.html', {'prefer_my_comment_form':prefer_my_comment_form})

#     else:
#         raise PermissionDenied

Chooser/prefer/templates/prefer_create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'css/prefer_create.css'%}">
    <title>Chooser - 취향소개 글쓰기</title>
</head>
<body>
<div class="all_pre_create">
    <!-- 상단(로고, 주제) -->
    <a href="{% url 'to_main' %}" class="main_logo_warper">
        <img src="{% static 'Img/logo.png' %}" class="main_logo">
    </a>
    <!-- 주제: {{topic_content}} -->
    <h1>금주의 주제: 라면 끼리는 법!!!!!!</h1>
    <h3>※주의할 점※</h3>
    <h4>이미지를 꼭 첨부해주세요 >_0<h4>
    <p>안 그러면 에러남 ㅠㅡㅜ....<p>

    <!-- 제목&내용&버튼 -->
    <div class="create_prefer">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{prefer_form.as_p}}
        <input type="submit" value="확인">
    </form>

</div>
</body>
</html>

Chooser/prefer/templates/prefer_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'css/prefer_detail.css'%}">
    <title>Chooser - 취향</title>
</head>
<body>
<div class="all_pre_detail">
    <!-- 상단(로고, 주제) -->
    <a href="{% url 'to_main' %}" class="main_logo_warper">
        <img src="{% static 'Img/logo.png' %}" class="main_logo">
    </a>
    <!-- 주제: {{topic_content}} -->
    <h1>금주의 주제: 라면 끼리는 법!!!!!!</h1>

    <!-- 내용 -->
    <p>제목: {{my_prefer.prefer_title}}</p>
    <p>작성자: {{my_prefer.prefer_member_id}}</p>
    <div class="img_prefer">
        <p>
            <img src="{{ my_prefer.prefer_file.url }}" >
        </p>
    </div>
    <p>{{my_prefer.prefer_content}}</p>
    <p>{{my_prefer.prefer_date|date:"Y.m.d"}}</p>

    
    <!-- 버튼 -->
    <!-- <button>좋아요</button> -->
    {% if user == my_prefer.prefer_member_id %}
        <a href="{% url 'prefer_update' my_prefer.prefer_id %}"><button>수정</button></a>
        <a href="{% url 'prefer_delete' my_prefer.prefer_id %}"><button>삭제</button></a>
    {% endif%}
    <div class="button">
        <a href="{% url 'prefer_index' %}"><button>목록</button></a>
    </div>

    <!-- 댓글기능 -->
    <br>
    <!-- create_comment url 문제 -->
    {% if user.is_authenticated %}
        <form method="POST" action="{% url 'prefer_create_comment' my_prefer.prefer_id %}">
            {% csrf_token %}        
            {{prefer_comment_form}}
            <input class="button" type="submit" value="댓글달기!">
        </form>
    {% endif %}

    {% comment %} {% for prefer_comment in my_prefer.prefer_comment_set.all %} -> comment_prefer로 해야되는데 잘못했엇움! {% endcomment %}

<!-- 댓글 수정&삭제 -->
{% for comment_prefer in my_prefer.comment_prefer_set.all %}

<p>
    {{comment_prefer.com_pre_member_id}} 🤦‍♂️ {{comment_prefer.com_pre_content}}
    {% if user == comment_prefer.com_pre_member_id %}
    {% comment %} <a href="{% url 'prefer_update_comment' my_prefer.prefer_id comment_prefer.com_pre_id %}"> 
       
        <button>수정</button>
    </a> {% endcomment %}
    <div class="button">
        <a href="{% url 'prefer_delete_comment' my_prefer.prefer_id comment_prefer.com_pre_id %}">    
            <button>삭제</button>
        </a>
    </div>
    {% endif %}
</p>

{% endfor %}





    {% comment %} <br>
    <textarea cols="50" rows="2" name="fulltext" placeholder="댓글을 입력하세요!"></textarea>
    <button>댓글달기</button> {% endcomment %}
</div>
</body>
</html>

Chooser/prefer/templates/prefer_index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{%static 'css/prefer_index.css'%}">
  <!-- Bootstrap core CSS -->
  <!-- CSS only -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

  <!-- JS, Popper.js, and jQuery -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous">
  </script>
  <title>Chooser - 취향목록</title>
</head>

<body>
  {% if user.is_authenticated %}

  <a href="{% url 'logout' %}">
    <button>로그아웃</button>
  </a>

  안녕하세요! {{user}}님!

  {% else %}
  <div class="button">
    <a href="{% url 'signup' %}">
      <button>회원가입</button>
    </a>
    <div>

      <div class="button">
        <a href="{% url 'login' %}">
          <button>로그인</button>
        </a>
      </div>

      {% endif %}
      <!-- 버튼 -->
      {% if user.is_authenticated %}
      <div class="make_prefer">
        <a href="{% url 'prefer_create' %}">
          <div class="plus_btn">
            <button>글쓰기</button>
          </div>
        </a>
      </div>
      {% endif %}

      <div class="all_pre_index">
        <!-- 상단(로고, 주제) -->
        <a href="{% url 'to_main' %}" class="main_logo_warper">
          <img src="{% static 'Img/logo.png' %}" class="main_logo">
        </a>
        <!-- 주제: {{topic_content}} -->
        <h1>금주의 주제: 라면 끼리는 법!!!!!!</h1>

        {% for prefer in posts %}

        <span class="big_box">
          <div class="col-lg-3 col-md-6 mb-4">
            <div class="card h-100">
              <div class="big_preview_prefer">
                <img class="card-img-top" src="{{ prefer.prefer_file.url }}"
                  alt="{% static 'Img/Chooser_preview.png' %}">
              </div>
              <div class="card-body">
                <h4 class="card-title">{{prefer.prefer_member_id}}</h4>
                <p class="card-text">{{prefer.prefer_title}}</p>
                <p class="card-text">{{prefer.prefer_content}}</p>
                <p class="card-text">{{prefer.prefer_date|date:"Y.m.d"}}</p>
              </div>
              <div class="card-footer">
                <a href="{% url 'prefer_detail' prefer.prefer_id %}">
                  <div class="btn btn-primary">
                    자세히 보기!
                  </div>
                </a>
              </div>
            </div>
          </div>
        </span>
        {% endfor %}

        <div class="make_prefer_index">
          {% comment %} {{%  %}} {% endcomment %}
        </div>

        <!-- 페이지네이션 -->
        <!-- https://imyeonn.github.io/blog/blog/142/ -->
        <!-- 시간 남으면 위의 코드 참조 이쁘게 꾸미기 -->
        <div class="prefer_pagination">
          <!-- 이전 페이지(True일 시) 불러오기 -->
          {% if posts.has_previous %}
          <a href="?page=1">맨 앞으로</a>
          <a href="?page={{posts.previous_page_number}}">이전으로</a>
          {% endif %}

          <!-- 현재&총 페이지 넘버 불러오기 -->
          <span>{{posts.number}}</span>
          <span>/</span>
          <span>{{posts.paginator.num_pages}}</span>

          <!-- 다음 페이지(True일 시) 불러오기-->
          {% if posts.has_next %}
          <a href="?page={{posts.next_page_number}}">다음으로</a>
          <a href="?page={{posts.paginator.num_pages}}">맨 뒤로</a>
          {% endif %}
        </div>
      </div>
</body>

</html>